### ISSUE TITLE
Compatibility of ::class is only with php 5.5

### ISSUE THREAD

**Issue by ecaradec** [huxia/apns2#1]
Hi,
You may want to change your compatibility level to 5.5 or fix it for 5.3 because of static::class feature you are using in Message.php. I would really like fixing it to 5.3 if you can though.

**Comment by huxia** [comment]
@ecaradec Thanks for your issue, i've made the fix. 

However, because JsonSerializable requires php 5.4, so this package still cannot works for 5.3.

I've change the compatibility to 5.4+.
